name: eai-vc
channels:
  - aihabitat
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - eigenpy=2.9.2
  - libglib=2.76.1
  - glib=2.76.1
  - glib-tools=2.76.1
  - black
  - click
  - cloudpickle
  - cffi
  - cmake=3.22.1
  - cudatoolkit=11.6
  - cython
  - flake8
  - glfw
  - habitat-sim=0.2.1
  - headless
  - hydra-core
  - ifcfg
  - isort
  - imageio
  - ipdb
  - ipython
  - jupyter
  - mamba
  - mkl-service
  - moviepy
  - numpy==1.23.4
  - opencv
  - pandas
  - patchelf
  - pinocchio
  - pillow
  - protobuf=3.20.1
  - pybullet
  - pytest
  - pytest-xdist
  - python=3.8
  - pytorch=1.13
  - pyyaml
  - scipy
  - seaborn
  - six
  - submitit
  - tabulate
  - tensorboard
  - termcolor
  - transforms3d
  - torchvision=0.14.0
  - tqdm
  - wandb>=0.13
  - wheel
  - yacs
  - pip
  - pip:
    - hydra-submitit-launcher
    - dm-control==1.0.5
    - gym==0.23.1
    - setuptools==59.5.0
    - timm==0.6.11
    - git+https://github.com/openai/CLIP.git
    - functorch
    - torchrl
    - classy_vision==0.6.0
    - yt_dlp==2023.2.17